object Versions {
    val coreKtxVer = "1.12.0"
    val appCompatVer = "1.6.1"
    val materialVer = "1.10.0"
    val constraintLayoutVer = "2.1.4"
    val kotlinCoroutinesVer = "1.7.2"
    val apolloClientVer = "3.8.2"
    val okhttpClientVer = "4.11.0"
    val navigation = "2.7.4"
    val pagingVer = "3.1.0"
    val glideVer = "4.16.0"
    val hiltVer = "2.48"
    val roomVer = "2.6.0"
    val junitVer = "4.13.2"
    val extJunitVer = "1.1.5"
    val espressoVer = "3.5.1"
}

object Dependencies {
    val coreKtx = "androidx.core:core-ktx:${Versions.coreKtxVer}"
    val appCompat = "androidx.appcompat:appcompat:${Versions.appCompatVer}"
    val material = "com.google.android.material:material:${Versions.materialVer}"
    val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayoutVer}"
    val kotlinCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlinCoroutinesVer}"
    val apolloClient = "com.apollographql.apollo3:apollo-runtime:${Versions.apolloClientVer}"
    val okhttpClient = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttpClientVer}"
    val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    val navigationUiKtx = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    val paging = "androidx.paging:paging-runtime-ktx:${Versions.pagingVer}"
    val glide = "com.github.bumptech.glide:glide:${Versions.glideVer}"
    val hilt = "com.google.dagger:hilt-android:${Versions.hiltVer}"
    val kaptHilt = "com.google.dagger:hilt-android-compiler:${Versions.hiltVer}"
    val roomKtx = "androidx.room:room-ktx:${Versions.roomVer}"
    val roomRuntime = "androidx.room:room-runtime:${Versions.roomVer}"
    val roomCompiler = "androidx.room:room-compiler:${Versions.roomVer}"
    val junit = "junit:junit:${Versions.junitVer}"
    val extJunit = "androidx.test.ext:junit:${Versions.extJunitVer}"
    val espresso = "androidx.test.espresso:espresso-core:${Versions.espressoVer}"
}